### ISSUE TITLE
After deleting mod I can't enter the end

### ISSUE THREAD

**Issue by arhp777** [koharas-Basement/Stellarity-Archive#4]
When I try to enter portal in worlds, which were created before deleting, the portal doesn't teleport me
version of mc: 1.20.1 forge
version of mod: v2-0e

**Comment by PikachuGabe** [comment]
This is currently just an archive of older versions of Stellarity I obtained through bisecting the source code, uploads from Kohara and the development repository.
However to fix your issue, try recreating the end portal using creative mode. I don't know enough about the ender portal handling on that ancient, end of support version.
